/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javagree */

#ifndef _Included_javagree
#define _Included_javagree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javagree
 * Method:    filagreeEval
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_javagree_filagreeEval
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
