/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Javagree */

#ifndef _Included_Javagree
#define _Included_Javagree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Javagree
 * Method:    evalSource
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_Javagree_evalSource
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject, jobjectArray);

/*
 * Class:     Javagree
 * Method:    evalBytes
 * Signature: (Ljava/lang/Object;Ljava/lang/String;[BLjava/lang/Object;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_Javagree_evalBytes
  (JNIEnv *, jobject, jobject, jstring, jbyteArray, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
