/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Javagree_Sys */

#ifndef _Included_Javagree_Sys
#define _Included_Javagree_Sys
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
