/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Javagree */

#ifndef _Included_Javagree
#define _Included_Javagree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Javagree
 * Method:    eval
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Javagree_eval
  (JNIEnv *, jobject, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
