/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Javagree_Test */

#ifndef _Included_Javagree_Test
#define _Included_Javagree_Test
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
